# Generated by Django 5.1.14 on 2026-06-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0086_alter_bot_meeting_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='meeting_dedup_key',
            field=models.CharField(blank=True, editable=False, help_text='Internal canonical meeting fingerprint used to enforce one active bot per meeting per project', max_length=512, null=True),
        ),
        migrations.AddConstraint(
            model_name='bot',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', [1, 2, 3, 4, 5, 8, 11, 12, 13, 14, 15, 16])), fields=('project', 'meeting_dedup_key'), name='unique_bot_meeting_dedup_key'),
        ),
    ]
