# Generated by Django 5.1.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0087_bot_meeting_dedup_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchatmessagerequest',
            name='to',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('specific_user', 'Specific User'), ('everyone_but_host', 'Everyone But Host')], max_length=255),
        ),
    ]
