# Generated by Django 5.1.14 on 2026-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0088_alter_botchatmessagerequest_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='session_type',
            field=models.IntegerField(choices=[(1, 'Bot'), (2, 'App Session'), (3, 'Local Recording')], db_default=1, default=1),
        ),
    ]
