# Generated by Django 5.1.14 on 2026-07-20 11:42

from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # Non-atomic so both index operations can run CONCURRENTLY: `bots` is large in prod, and a
    # plain index build takes an ACCESS EXCLUSIVE lock for its whole duration (blocking writes).
    #
    # The order is deliberately the reverse of what makemigrations produced: the new index is
    # built and valid BEFORE the old one is dropped, so owner lookups are never left without an
    # index. Dropping the old one is then safe because owner_user_id is the leading column of the
    # new index, so everything the old index served, the new one serves too.
    #
    # If a CONCURRENTLY build fails part-way, Postgres leaves an INVALID index behind that has to
    # be dropped by hand before re-running. Queries ignore it, so nothing breaks meanwhile.
    atomic = False

    dependencies = [
        ('bots', '0090_bot_owner_user_id'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='bot',
            index=models.Index(condition=models.Q(('owner_user_id__isnull', False)), fields=['owner_user_id', '-created_at', '-id'], name='bot_owner_history_idx'),
        ),
        RemoveIndexConcurrently(
            model_name='bot',
            name='bot_owner_user_id_idx',
        ),
    ]
