# Generated by Django 5.1.14 on 2026-07-19 16:29

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # Non-atomic so the index can be built CONCURRENTLY: `bots` is large in prod, and a plain
    # AddIndex would take an ACCESS EXCLUSIVE lock for the whole build (blocking writes). The
    # AddField is a nullable column with no default -> a metadata-only change on Postgres, so it
    # stays instant even outside a transaction.
    atomic = False

    dependencies = [
        ('bots', '0090_alter_botevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='owner_user_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        AddIndexConcurrently(
            model_name='bot',
            index=models.Index(condition=models.Q(('owner_user_id__isnull', False)), fields=['owner_user_id'], name='bot_owner_user_id_idx'),
        ),
    ]
