# Generated by Django 5.1.14 on 2026-07-24 19:09

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


def backfill_viewers_from_owner(apps, schema_editor):
    """Seed viewer_user_ids with the owner, so existing history stays visible after the read
    query switches from owner_user_id to viewer containment. An owned meeting starts with its
    owner as its sole viewer; an unowned one keeps the empty default and belongs to nobody,
    exactly as before. Batched to keep the working set bounded on a large table."""
    Bot = apps.get_model("bots", "Bot")
    batch = []
    # Only rows still on the empty default, so re-running never clobbers a viewer list that a
    # share has already grown past its owner.
    owned = Bot.objects.filter(owner_user_id__isnull=False).exclude(owner_user_id="").filter(viewer_user_ids=[])
    for bot in owned.iterator(chunk_size=1000):
        bot.viewer_user_ids = [bot.owner_user_id]
        batch.append(bot)
        if len(batch) >= 1000:
            Bot.objects.bulk_update(batch, ["viewer_user_ids"])
            batch = []
    if batch:
        Bot.objects.bulk_update(batch, ["viewer_user_ids"])


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0092_replace_bot_owner_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='viewer_user_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, editable=False, size=None),
        ),
        # Backfill before the index is created, so it is built on the finished data.
        migrations.RunPython(backfill_viewers_from_owner, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='bot',
            index=django.contrib.postgres.indexes.GinIndex(fields=['viewer_user_ids'], name='bot_viewers_gin'),
        ),
    ]
