# Generated by Django 5.1.14 on 2026-07-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0093_bot_viewer_user_ids_bot_bot_viewers_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='bots.bot')),
            ],
        ),
    ]
