# Generated by Django 5.1.14 on 2026-08-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0095_alter_credentials_credential_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="summary_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bot",
            name="summary_state",
            field=models.CharField(choices=[("pending", "Pending"), ("generating", "Generating"), ("done", "Done"), ("failed", "Failed"), ("skipped", "Skipped")], default="pending", max_length=20),
        ),
    ]
