# Generated by Django 5.1.14 on 2026-08-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0096_bot_summary_bot_summary_generated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="summary_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
