# Generated by Django 5.1.14 on 2026-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0097_bot_summary_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="summary_started_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
