# Generated by Django 5.1.14 on 2026-08-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0098_bot_summary_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='owner_user_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
