apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meeting-utility-ingress
  namespace: meeting-utility
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - meet-auth.apps.wisflux.com
        - attendee.apps.wisflux.com
        - attendee-minio.apps.wisflux.com
      secretName: wisflux-apps-tls
  rules:
    - host: meet-auth.apps.wisflux.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-server
                port:
                  number: 3001
    - host: attendee.apps.wisflux.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: attendee-web
                port:
                  number: 8000
    - host: attendee-minio.apps.wisflux.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
