# Generated by Django 5.1.14 on 2026-07-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0087_bot_meeting_dedup_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('team_day_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('org_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('org_id', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('bot', 'Bot'), ('live', 'Live')], max_length=8)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('platform', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Ended'), (3, 'Failed')], default=1)),
                ('summary_state', models.IntegerField(choices=[(1, 'Pending'), (2, 'Running'), (3, 'Done'), (4, 'Failed')], default=1)),
                ('language', models.CharField(blank=True, max_length=16, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bots.bot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='notes.appuser')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bots.project')),
            ],
        ),
        migrations.CreateModel(
            name='LiveUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uuid', models.CharField(max_length=255, null=True)),
                ('speaker', models.CharField(max_length=32)),
                ('source', models.IntegerField(choices=[(1, 'Mic'), (2, 'System')])),
                ('timestamp_ms', models.BigIntegerField()),
                ('duration_ms', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('transcription', models.JSONField(default=None, null=True)),
                ('failure_data', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='notes.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('content', models.JSONField()),
                ('model', models.CharField(max_length=128)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='notes.meeting')),
            ],
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['owner', '-started_at'], name='mtg_owner_started_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['org_id', '-started_at'], name='mtg_org_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('bot__isnull', False), ('deleted_at__isnull', True)), fields=('owner', 'bot'), name='uniq_meeting_owner_bot'),
        ),
        migrations.AddIndex(
            model_name='liveutterance',
            index=models.Index(fields=['meeting', 'timestamp_ms', 'id'], name='liveutt_meeting_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='liveutterance',
            constraint=models.UniqueConstraint(fields=('meeting', 'source_uuid'), name='uniq_utterance_meeting_srcuuid'),
        ),
    ]
