apiVersion: v1
kind: Secret
metadata:
  name: attendee-secret
  namespace: meeting-utility
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "CHANGEME_generate_with_python_-c_import_secrets_print_secrets.token_hex_50"
  CREDENTIALS_ENCRYPTION_KEY: "CHANGEME_generate_with_python_-c_from_cryptography.fernet_import_Fernet_print_Fernet.generate_key().decode()"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "CHANGEME_strong_password"
  POSTGRES_USER: "pgadmin"
  POSTGRES_PASSWORD: "CHANGEME_strong_password"
