apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: meeting-utility
type: Opaque
stringData:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "CHANGEME_strong_password"
  MINIO_BROWSER_REDIRECT_URL: "https://attendee-store.apps.wisflux.com/console"
