"""
Django settings for attendee project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import copy
import os
from pathlib import Path

from dotenv import load_dotenv

from attendee.sentry import init_sentry

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "accounts",
    "bots",
    "notes",
    "rest_framework",
    "concurrency",
    "allauth.socialaccount.providers.google",
    "drf_spectacular",
    "storages",
    "django_extensions",
]

CREDENTIALS_ENCRYPTION_KEY = os.getenv("CREDENTIALS_ENCRYPTION_KEY")

AUTH_USER_MODEL = "accounts.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Django allauth config
SITE_ID = 1
if os.getenv("DISABLE_SIGNUP") and os.getenv("DISABLE_SIGNUP") != "false":
    ACCOUNT_ADAPTER = "accounts.adapters.NoNewUsersAccountAdapter"
else:
    ACCOUNT_ADAPTER = "accounts.adapters.StandardAccountAdapter"
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_UNIQUE_EMAIL = True
LOGIN_REDIRECT_URL = "/"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_ENABLED = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_EMAIL_REQUIRED = True

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "csp.middleware.CSPMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "attendee.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "accounts", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "attendee.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Redis/Celery Configuration
redis_params = {}
if os.getenv("DISABLE_REDIS_SSL"):  # backward compatibility
    redis_params["ssl_cert_reqs"] = "none"
elif os.getenv("REDIS_SSL_REQUIREMENTS"):
    redis_params["ssl_cert_reqs"] = os.getenv("REDIS_SSL_REQUIREMENTS")
redis_params_query_string = "&".join([f"{key}={value}" for key, value in redis_params.items()])

REDIS_URL_WITH_PARAMS = os.getenv("REDIS_URL") + ("?" + redis_params_query_string if redis_params_query_string else "")

CELERY_BROKER_URL = REDIS_URL_WITH_PARAMS
CELERY_RESULT_BACKEND = REDIS_URL_WITH_PARAMS
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_ROUTES = {
    "bots.tasks.process_utterance_task.process_utterance": {
        "queue": os.getenv("PROCESS_UTTERANCE_CELERY_QUEUE", "celery"),
    },
    "bots.tasks.process_utterance_group_for_async_transcription_task.process_utterance_group_for_async_transcription": {
        "queue": os.getenv("PROCESS_UTTERANCE_CELERY_QUEUE", "celery"),
    },
    "bots.tasks.process_async_transcription_task.process_async_transcription": {
        "queue": os.getenv("PROCESS_ASYNC_TRANSCRIPTION_CELERY_QUEUE", "celery"),
    },
    "bots.tasks.sync_calendar_task.sync_calendar": {
        "queue": os.getenv("SYNC_CALENDAR_CELERY_QUEUE", "celery"),
    },
    "bots.tasks.launch_scheduled_bot_task.launch_scheduled_bot": {
        "queue": os.getenv("LAUNCH_SCHEDULED_BOT_CELERY_QUEUE", "celery"),
    },
    "bots.tasks.launch_adhoc_bot_task.launch_adhoc_bot": {
        "queue": os.getenv("LAUNCH_ADHOC_BOT_CELERY_QUEUE", "celery"),
    },
    "bots.tasks.deliver_webhook_task.deliver_webhook": {
        "queue": os.getenv("DELIVER_WEBHOOK_CELERY_QUEUE", "celery"),
    },
}

if os.getenv("LAUNCH_BOT_METHOD") != "kubernetes" and os.getenv("LAUNCH_BOT_METHOD") != "docker-compose-multi-host":
    # This setting means that each celery worker process will be recreated after each task.
    # Needed because latest Zoom SDK has segfault issue unless we recreate the process after each bot.
    CELERY_WORKER_MAX_TASKS_PER_CHILD = 1

if os.getenv("IS_A_BOT_POD", "false") == "true" and os.getenv("CONSERVE_BOT_POD_REDIS_CONNECTIONS", "false") == "true":
    # Setting this to 1 means that bot pods keep one celery broker pool connection alive for the duration of the bot.
    # Note: this results in 2 underlying Redis connections (one for commands, one for pub/sub).
    # Setting this to 0 means that no dedicated redis connection is created.
    # Instead bot pods will create and close a redis connection each time they need to execute a celery task.
    CELERY_BROKER_POOL_LIMIT = int(os.getenv("BOT_POD_CELERY_BROKER_POOL_LIMIT", 1))
    CELERY_TASK_IGNORE_RESULT = True

REST_FRAMEWORK = {
    # YOUR SETTINGS
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        "project_post": os.getenv("PROJECT_POST_THROTTLE_RATE", "3000/min"),
    },
}

DISABLE_RATE_LIMITING = os.getenv("DISABLE_RATE_LIMITING", "false") == "true"
SPECTACULAR_SETTINGS = {
    "TITLE": "Attendee API",
    "DESCRIPTION": "Meetings bots made easy",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "PARSER_WHITELIST": ["rest_framework.parsers.JSONParser"],
    "TAGS": [
        {"name": "Bots", "description": "Bot management endpoints"},
    ],
    "SERVERS": [
        {"url": "https://app.attendee.dev", "description": "Production server"},
    ],
}

# publish with python manage.py spectacular --color --file docs/openapi.yml

# Logging formatters - shared across environments
LOG_FORMATTERS = {
    "plain": {"format": "{levelname} {message}", "style": "{"},
    "json": {"class": "attendee.logging.ISOJsonFormatter", "format": "%(timestamp)s %(name)s %(levelname)s %(message)s"},
}

# Set up django storage backend
# Use s3 by default, but if the STORAGE_PROTOCOL env var is set to "azure", use azure storage
STORAGE_PROTOCOL = os.getenv("STORAGE_PROTOCOL", "s3")
AWS_RECORDING_STORAGE_BUCKET_NAME = os.getenv("AWS_RECORDING_STORAGE_BUCKET_NAME")
AZURE_RECORDING_STORAGE_CONTAINER_NAME = os.getenv("AZURE_RECORDING_STORAGE_CONTAINER_NAME")

# Audio chunk storage settings
USE_REMOTE_STORAGE_FOR_AUDIO_CHUNKS = os.getenv("USE_REMOTE_STORAGE_FOR_AUDIO_CHUNKS", "false") == "true"
FALLBACK_TO_DB_STORAGE_FOR_AUDIO_CHUNKS_IF_REMOTE_STORAGE_FAILS = os.getenv("FALLBACK_TO_DB_STORAGE_FOR_AUDIO_CHUNKS_IF_REMOTE_STORAGE_FAILS", "false") == "true"
AWS_AUDIO_CHUNK_STORAGE_BUCKET_NAME = os.getenv("AWS_AUDIO_CHUNK_STORAGE_BUCKET_NAME") or AWS_RECORDING_STORAGE_BUCKET_NAME
AZURE_AUDIO_CHUNK_STORAGE_CONTAINER_NAME = os.getenv("AZURE_AUDIO_CHUNK_STORAGE_CONTAINER_NAME") or AZURE_RECORDING_STORAGE_CONTAINER_NAME

if STORAGE_PROTOCOL == "azure":
    DEFAULT_STORAGE_BACKEND = {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "connection_string": os.getenv("AZURE_CONNECTION_STRING"),
            "account_key": os.getenv("AZURE_ACCOUNT_KEY"),
            "account_name": os.getenv("AZURE_ACCOUNT_NAME"),
            "expiration_secs": None if os.getenv("AZURE_STORAGE_USE_PERMANENT_LINKS", "false") == "true" else int(os.getenv("AZURE_STORAGE_LINK_EXPIRATION_SECONDS", 1800)),
        },
    }
    RECORDING_STORAGE_BACKEND = copy.deepcopy(DEFAULT_STORAGE_BACKEND)
    RECORDING_STORAGE_BACKEND["OPTIONS"]["azure_container"] = AZURE_RECORDING_STORAGE_CONTAINER_NAME

    AUDIO_CHUNK_STORAGE_BACKEND = copy.deepcopy(DEFAULT_STORAGE_BACKEND)
    AUDIO_CHUNK_STORAGE_BACKEND["OPTIONS"]["azure_container"] = AZURE_AUDIO_CHUNK_STORAGE_CONTAINER_NAME
else:
    DEFAULT_STORAGE_BACKEND = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "endpoint_url": os.getenv("AWS_ENDPOINT_URL"),
            "access_key": os.getenv("AWS_ACCESS_KEY_ID"),
            "secret_key": os.getenv("AWS_SECRET_ACCESS_KEY"),
        },
    }
    # Deep copy the DEFAULT_STORAGE_BACKEND
    RECORDING_STORAGE_BACKEND = copy.deepcopy(DEFAULT_STORAGE_BACKEND)
    RECORDING_STORAGE_BACKEND["OPTIONS"]["bucket_name"] = AWS_RECORDING_STORAGE_BUCKET_NAME

    AUDIO_CHUNK_STORAGE_BACKEND = copy.deepcopy(DEFAULT_STORAGE_BACKEND)
    AUDIO_CHUNK_STORAGE_BACKEND["OPTIONS"]["bucket_name"] = AWS_AUDIO_CHUNK_STORAGE_BUCKET_NAME


STORAGES = {
    "default": DEFAULT_STORAGE_BACKEND,
    "recordings": RECORDING_STORAGE_BACKEND,
    "bot_debug_screenshots": RECORDING_STORAGE_BACKEND,
    "audio_chunks": AUDIO_CHUNK_STORAGE_BACKEND,
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
AWS_S3_SIGNATURE_VERSION = "s3v4"
if os.getenv("USE_IRSA_FOR_S3_STORAGE", "false") == "true":
    AWS_S3_ADDRESSING_STYLE = "virtual"

CHARGE_CREDITS_FOR_BOTS = os.getenv("CHARGE_CREDITS_FOR_BOTS", "false") == "true"

BOT_POD_NAMESPACE = os.getenv("BOT_POD_NAMESPACE", "attendee")
WEBPAGE_STREAMER_POD_NAMESPACE = os.getenv("WEBPAGE_STREAMER_POD_NAMESPACE", "attendee-webpage-streamer")
REQUIRE_HTTPS_WEBHOOKS = os.getenv("REQUIRE_HTTPS_WEBHOOKS", "true") == "true"
REQUIRE_STRING_VALUES_IN_METADATA = os.getenv("REQUIRE_STRING_VALUES_IN_METADATA", "true") == "true"
MAX_METADATA_LENGTH = int(os.getenv("MAX_METADATA_LENGTH", 1000))
SITE_DOMAIN = os.getenv("SITE_DOMAIN", "app.attendee.dev")
MASK_TRANSCRIPT_IN_LOGS = os.getenv("MASK_TRANSCRIPT_IN_LOGS", "false") == "true"
ENFORCE_DOMAIN_ALLOWLIST_IN_CHROME = os.getenv("ENFORCE_DOMAIN_ALLOWLIST_IN_CHROME", "false") == "true"
CUSTOM_BOT_POD_SPEC_TYPES = os.getenv("CUSTOM_BOT_POD_SPEC_TYPES", "").split(",") if os.getenv("CUSTOM_BOT_POD_SPEC_TYPES") else []
GLOBAL_WEBHOOK_DELIVERIES_PER_SECOND_RATE_LIMIT = int(os.getenv("GLOBAL_WEBHOOK_DELIVERIES_PER_SECOND_RATE_LIMIT")) if os.getenv("GLOBAL_WEBHOOK_DELIVERIES_PER_SECOND_RATE_LIMIT") else None
LOG_BOT_STATE_CHANGES = os.getenv("LOG_BOT_STATE_CHANGES", "false") == "true"
LAUNCH_ADHOC_BOTS_ASYNC = os.getenv("LAUNCH_ADHOC_BOTS_ASYNC", "false") == "true"

# Content Security Policy
if os.getenv("ENABLE_CSP", "false") == "true":
    _csp_media_src = [d for d in os.getenv("CSP_MEDIA_SRC", "").split(",") if d]
    CONTENT_SECURITY_POLICY = {
        "DIRECTIVES": {
            "default-src": ["'self'"],
            "script-src": ["'self'", "'unsafe-inline'", "https://unpkg.com", "https://cdn.jsdelivr.net"],
            "style-src": ["'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net"],
            "font-src": ["'self'", "https://cdn.jsdelivr.net"],
            "img-src": ["'self'", "data:"] + _csp_media_src,
            "media-src": ["'self'"] + _csp_media_src,
            "connect-src": ["'self'", "https://cdn.jsdelivr.net"],
            "frame-src": ["https://www.loom.com"],
            "base-uri": ["'self'"],
            "form-action": ["'self'", "https://*.stripe.com"],
        },
    }

# Initialize Sentry (only if SENTRY_DSN is set)
init_sentry()
