apiVersion: v1
kind: Service
metadata:
  name: attendee-webpage-streamer
  namespace: meeting-utility
spec:
  selector:
    app: attendee-webpage-streamer
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
